spring.datasource.url=jdbc:mysql://localhost:3306/tree_navigator?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=020822
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true