CREATE TABLE sessions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT,
    user_id VARCHAR(50) NOT NULL COMMENT,
    title VARCHAR(255) NULL COMMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT,
    
    CONSTRAINT fk_sessions_user_id FOREIGN KEY (user_id) REFERENCES users(login_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT,
    session_id BIGINT NOT NULL COMMENT,
    role ENUM('USER', 'ASSISTANT') NOT NULL COMMENT,
    content TEXT NOT NULL COMMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT,
    CONSTRAINT fk_history_session_id FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;